apiVersion: v1
kind: Secret
metadata:
  name: {{ include "skillcanon.app.fullname" . }}
  labels:
    {{- include "skillcanon.labels" . | nindent 4 }}
    {{- include "skillcanon.app.selectorLabels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- if not .Values.externalDatabase.existingSecret }}
  database-url: {{ include "skillcanon.databaseUrl" . | b64enc | quote }}
  auth-database-url: {{ include "skillcanon.authDatabaseUrl" . | b64enc | quote }}
  migration-database-url: {{ include "skillcanon.migrationDatabaseUrl" . | b64enc | quote }}
  {{- end }}
  {{- if .Values.database.enabled }}
  postgresql-password: {{ .Values.secrets.postgresPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.app.smtp.enabled }}
  smtp-pass: {{ .Values.secrets.smtpPass | b64enc | quote }}
  {{- end }}
  {{- if .Values.app.github.enabled }}
  github-token: {{ .Values.secrets.githubToken | b64enc | quote }}
  {{- end }}
